---
- name: Hello Ansible - https://gist.github.com/Lewiscowles1986/fecd4de0b45b2029c390
  hosts: rpi
  become_user: root
  become: yes

  tasks:    
    - name: Update apt-get cache
      apt: >
        update_cache=yes
        cache_valid_time=3600
   
    - name: Update all packages to the latest version
      apt: > 
        upgrade=yes
 
    - name: Add the archive's GPG key get
      get_url:
        url: https://apt.mopidy.com/mopidy.gpg
        dest: /tmp/mopidy.gpg
    - name: Add the archive's GPG key execute
      command: apt-key add /tmp/mopidy.gpg

    - name: Update the repository cache and update package "mopidy" to latest version using default release squeeze-backport
      apt:
        name: mopidy
        state: latest
        update_cache: yes

    - name: Install list of packages
      action: apt pkg={{item}} state=installed
      with_items:
        - mopidy

    - name: Install list of pip packages
      action: pip name={{item}}
      with_items:
        - mopidy_MFE 
        - Mopidy-CarPi 
        - Mopidy-jukePi 
        - Mopidy-Auto 
        - Mopidy-WebSettings 
        - Mopidy-Terminal 
        - Mopidy-MusicBox-Webclient
        - Mopidy-Moped
        - Mopidy-Simple-Webclient
        - Mopidy-Mobile
        - Mopidy-API-Explorer
        - Mopidy-WebLibrary
        - Mopidy-AlarmClock
        - Mopidy-PlaybackDefaults
        - Mopidy-Material-Webclient
    - name: mopidy.conf
      copy:
        src: ./mopidy.conf
        dest: /etc/mopidy/mopidy.conf
    - name: mopidy local scan
      command: mopidy local scan

    - name: mopidy start service 
      service: 
        name: mopidy
        state: started
